"""Overlap / lineage reconstruction + confidence + attribution."""

from __future__ import annotations

import datetime
import logging
import os
import re

from receipts import gitobjects as git
from receipts import license as _lic
from receipts.models import Overlap, AttributionDiff

logger = logging.getLogger(__name__)

# Boilerplate / common paths that carry ~no provenance signal on their own.
# A shared LICENSE or empty .gitignore proves nothing (millions share them).
_COMMON_BASENAMES = {
    ".gitignore", ".gitattributes", ".editorconfig", ".dockerignore",
    "license", "license.md", "license.txt", "licence", "copying",
    "readme.md", "readme", "readme.txt", "requirements.txt", "package.json",
    "package-lock.json", "yarn.lock", "poetry.lock", "makefile", "dockerfile",
    "__init__.py", "py.typed", ".gitkeep",
}
_MIN_DISTINCTIVE_BYTES = 64  # tiny files are usually boilerplate

# Vendored / third-party directories. Two unrelated projects that bundle the same
# dependency legitimately share those blobs — counting them as provenance evidence
# is the single biggest false-positive source (SPEC §16). Caught for real by
# pip vs setuptools, which both vendor `packaging` (23 "distinctive" shared files).
_VENDOR_MARKERS = (
    "/vendor/", "/_vendor/", "/vendored/", "/third_party/", "/thirdparty/",
    "/3rdparty/", "/node_modules/", "/external/", "/deps/", "/dist-info/",
    "/site-packages/", "/bundled/", "/extern/", "/.yarn/",
)


def is_vendored(path: str) -> bool:
    p = "/" + path.replace("\\", "/").lower()
    return any(m in p for m in _VENDOR_MARKERS) or p.startswith(
        ("/vendor/", "/_vendor/", "/third_party/", "/node_modules/"))


def bundled_prefixes(paths) -> tuple[str, ...]:
    """Directories that carry their own licence file — bundled dependencies."""
    out = set()
    for path in paths:
        parts = path.replace("\\", "/").split("/")
        if len(parts) < 2:
            continue                       # the repo's own root licence
        base = parts[-1].lower()
        if base.startswith(("license", "licence", "copying", "notice")):
            out.add("/".join(parts[:-1]) + "/")

    # Promoting a parent that holds several of these was tried and reverted: in
    # BambuStudio the parent is `src/`, which also holds the project's entire own
    # codebase, and excluding it dropped the files examined from 711 to 44.
    # Third-party code is identified by WHOSE NOTICE IT CARRIES instead --- see
    # `expression.derived_unattributed`.
    return tuple(sorted(out))


# Markers that a file was produced by a program, taken from GitHub Linguist's
# `lib/linguist/generated.rb` — the reference implementation every code host
# already relies on, rather than a list invented here.
# https://github.com/github-linguist/linguist/blob/main/lib/linguist/generated.rb
_GENERATED_MARKERS = (
    "@generated", "do not edit", "code generated by", "generated by the protocol",
    "autogenerated by", "automatically generated", "this file is generated",
    "generated by cython", "machine generated",
)
_GENERATED_HEAD_LINES = 40          # Linguist scans the first 40 lines
_MINIFIED_AVG_LINE = 110            # Linguist: mean line length > 110 => minified
_MINIFIED_EXT = (".js", ".css")
_LOCKFILE_NAMES = (
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "poetry.lock",
    "cargo.lock", "gemfile.lock", "composer.lock", "go.sum", "pdm.lock",
    "packages.lock.json", "flake.lock", "uv.lock",
)


def is_machine_generated(path: str, text: str) -> bool:
    """Was this file produced by a program rather than written by a person?"""
    name = os.path.basename(path).lower()
    if name in _LOCKFILE_NAMES:
        return True
    if "__generated__/" in path or path.endswith((".designer.cs", ".designer.vb")):
        return True
    lines = text.splitlines()
    if not lines:
        return False
    head = "\n".join(lines[:_GENERATED_HEAD_LINES]).lower()
    if any(m in head for m in _GENERATED_MARKERS):
        return True
    if path.lower().endswith(_MINIFIED_EXT):
        return sum(len(l) for l in lines) / len(lines) > _MINIFIED_AVG_LINE
    return False


def _is_distinctive(repo: str, path: str, sha: str) -> bool:
    base = os.path.basename(path).lower()
    if base in _COMMON_BASENAMES:
        return False
    if is_vendored(path):
        return False
    text = git.blob_text(repo, sha)
    # Machine output is identical across unrelated projects by construction, so
    # it carries no provenance signal however large it is. Checked before the
    # size test because minified bundles are large, which is exactly why they
    # used to survive it.
    if is_machine_generated(path, text):
        return False
    # very small blobs are noise
    return len(text.encode("utf-8", "ignore")) >= _MIN_DISTINCTIVE_BYTES


def commit_overlap(a: str, b: str) -> tuple[set[str], int, int]:
    ca, cb = git.all_commits(a), git.all_commits(b)
    shared = ca & cb
    logger.info("commit overlap: upstream=%d suspect=%d shared=%d",
                len(ca), len(cb), len(shared))
    return shared, len(ca), len(cb)


def most_recent_common_commit(suspect: str, shared: set[str]) -> tuple[str | None, str | None]:
    """The newest commit on the suspect's mainline that the upstream also has."""
    if not shared:
        return None, None
    for line in git.first_parent_log(suspect):
        sha, _, date = line.partition(" ")
        if sha in shared:
            return sha, date
    return None, None


def newest_shared_on_mainline(upstream: str, suspect: str) -> str | None:
    """Newest commit on the upstream's mainline that the suspect's HEAD reaches.

    Not "that the suspect HOLDS". A fork's clone keeps the upstream's other
    branches, and objects sitting in a ref nobody builds from say nothing about
    what the fork was taken from. openbao/openbao carries 2,195 Vault commits
    its own line never reaches; picking one of them moved the anchor from
    2023-05-26 to 2024-03-18, across HashiCorp's relicensing, and the report
    stated that OpenBao's code came from Vault under BUSL-1.1. It did not:
    zero post-BUSL Vault mainline commits are ancestors of openbao's HEAD.
    """
    have = git.ancestors(suspect, "HEAD")
    for line in git.first_parent_log(upstream):
        sha, _, _ = line.partition(" ")
        if sha in have:
            return sha
    return None


def anchor_commit(upstream: str, suspect: str,
                  common_commit: str | None) -> tuple[str, str]:
    """The upstream commit standing for its state WHEN THE SUSPECT DIVERGED."""
    # "Present in both repositories" is NOT "the upstream's state". A repo carries
    # commits written by other people — fetched pull-request refs, contributed
    # branches, mirrored forks. In Fly-By-Wire the newest shared commit sat on a
    # branch the FORK's owner had pushed, in which he had already deleted the
    # licence; reading it reported the upstream as unlicensed and exculpated the
    # party that removed it (BENCHMARK §F.2b).
    if common_commit and git.is_ancestor(upstream, common_commit):
        return common_commit, "most recent shared commit on the upstream's mainline"
    if common_commit:
        logger.warning("shared commit %s is not on the upstream's mainline "
                       "(likely a fetched fork/PR ref); searching for one that is",
                       common_commit[:10])
        # The newest shared commit can sit off the mainline while thousands of
        # perfectly good ones sit on it. Walking down to the first that is an
        # ancestor of the upstream's HEAD answers the actual question — the last
        # moment the two histories were the same — instead of giving up.
        #
        # Falling straight through to the date fallback got mapbox-gl-js wrong by
        # seven years: MapLibre is a whole-history fork, so "when the suspect's
        # history begins" is 2013, the UPSTREAM's first commit, and the licence
        # was read from a tree that had no LICENSE file yet. The divergence is
        # November 2020 (BSD-3-Clause), which this finds.
        sha = newest_shared_on_mainline(upstream, suspect)
        if sha:
            return sha, ("most recent shared commit on the upstream's mainline "
                         "(the newest shared commit overall was not on it)")
    # No usable shared history (derivation seen through identical files). Align by
    # date to when the suspect's own history begins. Deliberately the EARLIEST
    # plausible moment: if the code was actually taken later, this understates the
    # upstream's state, which errs towards not accusing.
    started = git.earliest_commit_date(suspect)
    sha = git.commit_at_or_before(upstream, started)
    if sha:
        return sha, f"upstream as of {started[:10]}, when the suspect's history begins"
    return "", "no anchor available"


def anchor_gap_days(upstream: str, anchor: str, newest_shared_date: str | None) -> int:
    """Days between the anchor and the newest commit BOTH repositories hold."""
    if not anchor or not newest_shared_date:
        return 0
    try:
        anchor_date = git.commit_date(upstream, anchor)
        a = datetime.date.fromisoformat(anchor_date[:10])
        b = datetime.date.fromisoformat(newest_shared_date[:10])
        return abs((b - a).days)
    except Exception:                                        # pragma: no cover
        return 0


def blob_overlap(a: str, b: str) -> tuple[int, int, int, list[str]]:
    """Returns (shared_blobs, total_blobs_b, distinctive_shared, distinctive_paths)."""
    ba, bb = git.all_blobs(a), git.all_blobs(b)
    shared = ba & bb
    logger.info("blob overlap: upstream=%d suspect=%d shared=%d", len(ba), len(bb), len(shared))
    # On a partial clone, reading blob contents (needed to judge "distinctive")
    # would lazily fetch each blob and hang. Skip the distinctive computation —
    # commit-SHA overlap is the signal for large forks anyway.
    if git.is_partial_clone(a) or git.is_partial_clone(b):
        logger.warning("partial clone detected: skipping distinctive-blob analysis "
                       "(reading blobs would trigger a lazy fetch of the whole tree)")
        return len(shared), len(bb), 0, []
    head_b = git.head_blobs(b)
    distinctive_paths = [
        path for path, sha in head_b.items()
        if sha in shared and _is_distinctive(b, path, sha)
    ]
    return len(shared), len(bb), len(distinctive_paths), sorted(distinctive_paths)


def attribution_diff(upstream: str, suspect: str,
                     upstream_ref_text: str | None = None,
                     suspect_license_text: str | None = None,
                     upstream_commit: str | None = None) -> AttributionDiff:
    au = git.authors(upstream)
    asus = git.authors(suspect)
    # Use the upstream license text AT DIVERGENCE (the original code notice), not
    # the upstream's CURRENT HEAD: if the upstream relicensed after the fork, its
    # HEAD license carries the new license's author (e.g. terraform's BSL is
    # authored by MariaDB) — comparing that produced false "notice stripped".
    if upstream_ref_text is None:
        upstream_ref_text = _lic.license_text(upstream, _lic.find_license(upstream))
    if suspect_license_text is None:
        suspect_license_text = _lic.license_text(suspect, _lic.find_license(suspect))
    up_text, su_text = upstream_ref_text, suspect_license_text
    up_holders = _lic.detect_holders(up_text)
    su_holders = _lic.detect_holders(su_text)
    up_holder = up_holders[0] if up_holders else ""
    # "Preserved" = ANY of the upstream's copyright holders still appears among
    # the suspect's notices. Must check ALL holders on both sides: a compliant
    # fork typically ADDS its own line first and keeps the original below
    # (OpenTofu keeps "© 2014 HashiCorp"; Valkey keeps "© 2006-2020 Redis Ltd.").
    # Matching is token-based because the holder may be renamed while the years
    # stay ("Salvatore Sanfilippo" → "Redis Ltd.").
    holder_present = _holders_overlap(up_holders, su_holders) or (
        git.count_spdx_headers(suspect) > 0
    )
    compared, replaced, dropped, examples, changed = header_diff(
        upstream, suspect, upstream_commit)
    return AttributionDiff(
        upstream_authors=sorted(au)[:20],
        suspect_authors=sorted(asus)[:20],
        upstream_authors_present_in_suspect=bool(au & asus),
        upstream_notice_present=bool(up_holder) or git.count_spdx_headers(upstream) > 0,
        suspect_notice_present=holder_present or git.count_spdx_headers(suspect) > 0,
        notice_stripped=bool(up_holder) and not holder_present,
        files_compared=compared, files_header_replaced=replaced,
        files_header_dropped=dropped, header_examples=examples,
        changed_header_paths=changed,
    )


# Source extensions where a license header is conventional.
_SRC_EXT = (".go", ".py", ".js", ".ts", ".java", ".c", ".h", ".cc", ".cpp",
            ".hpp", ".rs", ".rb", ".m", ".mm", ".cs", ".php", ".swift", ".kt")


def header_diff(upstream: str, suspect: str, upstream_commit: str | None = None,
                max_files: int = 400):
    """Notices the suspect PROVABLY held and no longer has."""
    if git.is_partial_clone(upstream) or git.is_partial_clone(suspect):
        logger.warning("partial clone detected: skipping attribution analysis")
        return 0, 0, 0, [], []

    up_blobs = git.all_blobs(upstream)
    current = git.head_blobs(suspect)
    bundled = bundled_prefixes(current)

    # Newest-first, so the most recent version the suspect held of each path wins.
    held: dict[str, str] = {}
    for oid, path in reversed(git.historical_objects(suspect)):
        if path in current and oid in up_blobs and path not in held \
                and path.lower().endswith(_SRC_EXT) \
                and not is_vendored(path) and not path.startswith(bundled):
            held[path] = oid
    held = dict(sorted(held.items())[:max_files])
    if not held:
        return 0, 0, 0, [], []
    logger.info("attribution: %d file(s) the suspect provably held from the "
                "upstream; checking whether their notices survive", len(held))

    # Only the UPSTREAM PROJECT's own attribution is evidence here. A notice
    # belonging to a third party — a bundled library's authors — says nothing
    # about how the suspect treated the upstream, and both repos usually carry it
    # because both vendored the same dependency at different versions. Naming
    # conventions keep missing these (`src/hidapi/`, `deps_src/libigl/`), so match
    # on WHOSE notice it is instead of where the file sits.
    up_holders = project_holders(upstream, upstream_commit)
    logger.info("upstream project holders: %s",
                ", ".join(sorted(up_holders)[:4]) or "(none identified)")
    # Notices belonging to a bundled dependency are NOT discarded: removing one is
    # still a real violation, only against that library's authors rather than the
    # upstream's. They are labelled with whose attribution was lost, so the report
    # names the right rightsholder. What IS suppressed is version drift — the
    # suspect upgrading a vendored library to a release where the same file is
    # attributed to a different contributor of that same project (OrcaSlicer's
    # libigl `cut_mesh.cpp` went from Alec Jacobson to Hanxiao Shen: both libigl).
    # A replacement is meaningful when the suspect put ITS OWN name on the file.
    # Third-party-to-third-party changes are ambiguous: OrcaSlicer's libigl
    # `cut_mesh.cpp` went from Alec Jacobson to Hanxiao Shen, both libigl
    # contributors — that is the vendored library being upgraded, not attribution
    # being taken. Only a notice naming the suspect supports a claim.
    suspect_holders = project_holders(suspect)

    was = git.batch_blob_text(suspect, list(held.values()))
    now = git.batch_blob_text(suspect, [current[p] for p in held])
    # What the UPSTREAM's own file says at the anchor. A fork inherits the whole
    # history, so "the suspect once held a blob carrying this notice" is often
    # just "the upstream once did" --- and if the upstream removed the notice
    # itself, the suspect inherited the result and did nothing.
    #
    # The first time this check ever fired outside the case it was built on, that
    # is exactly what it caught: `tests/modules/auth.c` carried
    # "Copyright 2019 Amazon.com, Inc.", and Redis removed it in a511a37bb
    # ("Fixed some documentation", 2019-12-17) --- a commit Valkey inherited,
    # five years before Valkey existed.
    up_now = git.blobs_at(upstream, upstream_commit or "HEAD")
    up_text = git.batch_blob_text(
        upstream, [up_now[p] for p in held if p in up_now])

    compared = replaced = dropped = 0
    examples: list[str] = []
    changed: list[str] = []
    for path, oid in held.items():
        had = _copyright_lines(was.get(oid, ""))
        if not had:
            continue                       # nothing to lose
        whose = ("the upstream project" if _holders_overlap(had, up_holders)
                 else _library_of(path, bundled) or "a third party")
        compared += 1
        has = _copyright_lines(now.get(current[path], ""))
        if _holders_overlap(had, has):
            continue
        if has and not _holders_overlap(has, suspect_holders):
            continue        # swapped for another third party — ambiguous, not a claim
        # The upstream's OWN successive identities are not a replacement. Synapse
        # was written by matrix.org, then OpenMarket Ltd, then The Matrix.org
        # Foundation C.I.C., then New Vector Ltd (Element) --- a decade of
        # corporate succession over one codebase. Comparing holder strings read
        # every one of those transitions as somebody taking credit, and reported
        # 32 of them (held-out #3). A holder the upstream itself uses anywhere in
        # its history is the same lineage.
        if has and _holders_overlap(has, up_holders):
            continue
        # Does the upstream still carry the notice it is said to have lost? If
        # its own file no longer does either, the removal happened upstream.
        up_blob = up_now.get(path)
        if up_blob is not None:
            up_had = _copyright_lines(up_text.get(up_blob, ""))
            if not _holders_overlap(up_had, had):
                continue
        changed.append(path)
        # `whose` names who the notice that was REPLACED belonged to. Trailing
        # it after the arrow put it next to the replacement, so Valkey's own
        # "Copyright Valkey Contributors." read as "[the upstream project]".
        was_line = f"'{had[0][:55]}' ({whose})"
        if has:
            replaced += 1
            if len(examples) < 5:
                examples.append(f"{path}: {was_line} -> '{has[0][:55]}'")
        else:
            dropped += 1
            if len(examples) < 5:
                examples.append(f"{path}: {was_line} -> (no notice)")
    return compared, replaced, dropped, examples, changed


def _library_of(path: str, bundled: tuple[str, ...]) -> str:
    """The bundled-library prefix a path sits under, or '' for the project's own code."""
    for pre in bundled:
        if path.startswith(pre):
            return pre.rstrip("/")
    return ""


def project_holders(repo: str, commit: str | None = None) -> list[str]:
    """Copyright notices that identify the project itself."""
    from collections import Counter
    ref = commit or "HEAD"
    holders: list[str] = []
    st = _lic.find_license(repo, ref)
    holders += _copyright_lines(_lic.license_text(repo, st))
    blobs = git.blobs_at(repo, ref)
    src = [sha for path, sha in blobs.items()
           if path.lower().endswith(_SRC_EXT) and not is_vendored(path)]
    texts = git.batch_blob_text(repo, src[:600], limit=1500)
    counter: Counter = Counter()
    for t in texts.values():
        for line in _copyright_lines(t):
            counter[" ".join(line.split())] += 1
    holders += [h for h, n in counter.most_common(12) if n >= 3]
    return [h for h in holders if h.strip()]


def _copyright_lines(text: str) -> list[str]:
    out = []
    for line in text.splitlines()[:40]:
        low = line.lower()
        if "copyright" in low or "\u00a9" in line:
            out.append(line.strip(" /*#-\t"))
    return out


def _notice_years(text: str) -> tuple[str, ...]:
    """Years mentioned in a copyright notice, e.g. ("2006", "2020")."""
    return tuple(re.findall(r"\b(?:19|20)\d{2}\b", text))


def _holders_overlap(a: list[str], b: list[str]) -> bool:
    """True if any upstream attribution is still recognizable in the derivative."""
    # Generic words that identify nobody — matching on them alone yields false
    # "attribution preserved" (e.g. "Orig Author" vs "GPL Author").
    _STOP = {"inc", "llc", "ltd", "corp", "corporation", "the", "and", "author",
             "authors", "contributors", "contributor", "project", "team", "co",
             "gmbh", "sa", "ab", "present", "copyright", "reserved", "rights",
             "all", "software", "foundation", "developers", "maintainers"}

    # Identical text is preserved attribution, full stop. Without this the token
    # logic can answer False for a notice that did not change at all: stripping
    # years and generic words from "Copyright 2009, All Rights Reserved." leaves
    # an empty set, and an empty set intersects nothing — four hidapi files were
    # reported as "replaced" with the same string on both sides.
    norm = {" ".join(x.split()).strip(" .,;:*/#-").lower() for x in a}
    if norm & {" ".join(y.split()).strip(" .,;:*/#-").lower() for y in b}:
        return True

    def toks(s: str) -> set[str]:
        s = re.sub(r"(?i)copyright|\(c\)|©|all rights reserved|[0-9]{4}", " ", s)
        return {t for t in s.lower().replace("/", " ").replace(",", " ").split()
                if t not in _STOP and len(t) > 2}

    for x in a:
        tx, yx = toks(x), _notice_years(x)
        for y in b:
            if tx and tx & toks(y):
                return True
            if yx and len(yx) > 1 and yx == _notice_years(y):
                return True   # same multi-year span → the historical line survived
    return False


# With no shared history at all, a derivation claim rests entirely on identical
# files. One or two of those are routinely explained by both sides having taken
# the file from the same third place, so they are reported as a lead to check,
# never as a finding. Held-out #3: gitea and synapse share zero commits and one
# file, and were called derived.
_MIN_BLOBS_WITHOUT_HISTORY = 3


def confidence_and_flags(ov: Overlap) -> tuple[str, bool, str]:
    """(confidence, derivation_likely, needs_review) from the strength of signal."""
    if ov.shared_commits and not ov.common_history_is_negligible:
        return "high", True, ""        # substantial shared lineage
    if ov.shared_commits:
        # Real shared objects, but a sliver — an old common ancestor or an import.
        return ("medium" if ov.distinctive_shared_blobs >= _MIN_BLOBS_WITHOUT_HISTORY
                else "low"), True, (
            f"only {ov.shared_commits} shared commit(s) — this can be a common "
            "ancestor or a single import rather than a fork; read them")
    if ov.distinctive_shared_blobs >= _MIN_BLOBS_WITHOUT_HISTORY:
        return "medium", True, (
            f"{ov.distinctive_shared_blobs} identical files but NO shared "
            "history — open each one and confirm it is not a third party's")
    if ov.distinctive_shared_blobs >= 1:
        return "none", False, (
            f"{ov.distinctive_shared_blobs} identical file(s) and no shared "
            "history: too little to call derivation, too much to ignore — "
            "listed below so you can look")
    return "none", False, ""


# --------------------------------------------------------------------------- #
# Shared history crossed with the origin's licence changes.
# --------------------------------------------------------------------------- #
def shared_by_licence_era(upstream: str, shared: set[str],
                          transitions) -> list[dict]:
    """How many shared commits fall under each licence the origin has carried.

    The newest shared commit is one moment; a fork taken from a release branch
    can share commits that straddle a relicensing. Counting per era answers
    which terms the shared code was actually available under.

    The licence in force at a commit is the one set by the newest licence-file
    change that commit descends from. Asking the other way round — which
    commits are ancestors of each change — is the same thing only on a strictly
    linear mainline, and every real repository has branches: it put 58% of what
    gogs shares with gitea (2,435 commits) and 35% of what redis shares with
    valkey into an "unattributable" row, including the whole final era, which is
    the one the fork was actually taken under.
    """
    if not shared or not transitions:
        return []
    remaining = set(shared)
    rows: list[dict] = []
    for t in reversed(transitions):                   # newest change first
        if not remaining:
            break
        # The change commit itself already carries the new licence.
        era = (git.descendants(upstream, t.commit) | {t.commit}) & remaining
        if era:
            rows.append({"licence": t.after_governing or t.after,
                         "commits": len(era),
                         "from_commit": t.commit, "from_date": t.date[:10]})
            remaining -= era
    rows.reverse()                                    # oldest era first
    first = transitions[0]
    if remaining:
        # Before the first licence-file commit on that line of history.
        before = git.ancestors(upstream, first.commit) & remaining
        if before:
            rows.insert(0, {"licence": first.before_governing or first.before,
                            "commits": len(before),
                            "from_commit": "", "from_date": ""})
            remaining -= before
    # Consecutive eras under the same grant were two rows because a bundled
    # dependency changed, which is not a relicensing of the project.
    merged: list[dict] = []
    for r in rows:
        if merged and merged[-1]["licence"] == r["licence"]:
            merged[-1]["commits"] += r["commits"]
            continue
        merged.append(r)
    rows = merged
    if remaining:
        # Neither ancestor nor descendant of any licence-file commit: an orphan
        # root, or a branch grafted in. Nothing about the licence follows from
        # the history, so nothing is claimed.
        rows.append({"licence": "", "commits": len(remaining),
                     "from_commit": "", "from_date": ""})
    return rows
